---
- name: tap for ricty
  homebrew_tap: tap=sanemat/font state=present

- name: install ricty
  homebrew:
    name: ricty
    state: latest
    install_options: powerline, vim-powerline

- name: get ricty version
  shell:  brew info ricty | fgrep stable
  register: ricty_version_tmp
  changed_when: False
  always_run: True

- name: get ricty version
  set_fact:
    ricty_version_dict:  "{{ ricty_version_tmp.stdout | from_yaml }}"

- name: get ricty version
  set_fact:
    ricty_version:  "{{ ricty_version_dict['sanemat/font/ricty']  | replace('stable', '') | trim }}"

- name: copy fonts
  copy:
    src: '{{ item }}'
    dest: ~/Library/Fonts/
  with_items:
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty Bold for Powerline.ttf
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty Regular for Powerline.ttf
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty-Bold-Powerline.ttf
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty-Bold.ttf
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty-Regular-Powerline.ttf
      - /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty-Regular.ttf
  notify: run fc-cache