---
- name: tap for ricty
  homebrew_tap: tap=sanemat/font state=present

#brew reinstall --powerline --vim-powerline ricty
- name: install ricty
  homebrew:
    name: ricty
    state: latest
    install_options: powerline, vim-powerline

- name: get ricty version
  shell:  brew info ricty | fgrep stable
  register: ricty_version_tmp
  changed_when: False
  always_run: True

- name: set ricty version
  set_fact:
    ricty_version_dict:  "{{ ricty_version_tmp.stdout | from_yaml }}"

- name: format ricty version
  set_fact:
    ricty_version:  "{{ ricty_version_dict['sanemat/font/ricty']  | replace('stable', '') | trim }}"

- name: copy fonts
  copy:
    src: /usr/local/Cellar/ricty/{{ ricty_version }}/share/fonts/Ricty\*.ttf
    dest: ~/Library/Fonts/
  notify: run fc-cache