- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - homebrew
    - homebrew-cask
    - mas
    - directories
    - sublime-text
  vars:
    local_dotfiles_ripository: ''
