- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    # - homebrew
    # - homebrew-cask
    # - mas
    # - directories
    - osx-defaults
  vars:
    local_dotfiles_ripository: ''
