---
    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - amazon-music
      - appcleaner
      - atom
      - betterzipql
      - chatwork
      - clipy
      - dash
      - datagrip
      - docker
      - duet
      - evernote
      - flux
      - google-chrome
      - google-drive
      - google-japanese-ime
      - iterm2
      - karabiner
      - keepassx
      - magican
      - postman
      - pritunl
      - qlcolorcode
      - qlimagesize
      - qlmarkdown
      - qlstephen
      - quicklook-csv
      - quicklook-json
      - sequel-pro
      - skitch
      - slack
      - sublime-text
      - vagrant
      - virtualbox
