---
    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - amazon-music
      - atom
      - chatwork
      - clipy
      - dash
      - docker
      - evernote
      - flux
      - google-chrome
      - google-drive
      - google-japanese-ime
      - iterm2
      - keepassx
      - mysqlworkbench
      - pritunl
      - sequel-pro
      - slack
      - vagrant
      - virtualbox

